#!/bin/bash
set -e

echo "Initializing TheLarte database schemas..."

# Create schemas for each microservice
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create schemas for microservices
    CREATE SCHEMA IF NOT EXISTS auth;
    CREATE SCHEMA IF NOT EXISTS users;
    CREATE SCHEMA IF NOT EXISTS inventory;
    CREATE SCHEMA IF NOT EXISTS sales;
    CREATE SCHEMA IF NOT EXISTS billing;
    
    -- Grant permissions
    GRANT ALL PRIVILEGES ON SCHEMA auth TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON SCHEMA users TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON SCHEMA inventory TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON SCHEMA sales TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON SCHEMA billing TO $POSTGRES_USER;
    
    -- Grant permissions on all tables in schemas
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA users TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA inventory TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sales TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA billing TO $POSTGRES_USER;
    
    -- Grant permissions on all sequences in schemas
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA users TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA inventory TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sales TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA billing TO $POSTGRES_USER;
    
    -- Set default privileges for future tables and sequences
    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO $POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA users GRANT ALL ON TABLES TO $POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT ALL ON TABLES TO $POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA sales GRANT ALL ON TABLES TO $POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT ALL ON TABLES TO $POSTGRES_USER;
    
    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO $POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA users GRANT ALL ON SEQUENCES TO $POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT ALL ON SEQUENCES TO $POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA sales GRANT ALL ON SEQUENCES TO $POSTGRES_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT ALL ON SEQUENCES TO $POSTGRES_USER;
EOSQL

echo "Database schemas initialization completed."
