server:
  port: 8083
  servlet:
    context-path: /sales

spring:
  application:
    name: sales-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sales_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
