#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create schemas for each service if they don't exist
    CREATE SCHEMA IF NOT EXISTS auth;
    CREATE SCHEMA IF NOT EXISTS user_service;
    CREATE SCHEMA IF NOT EXISTS inventory;
    CREATE SCHEMA IF NOT EXISTS sales;
    CREATE SCHEMA IF NOT EXISTS billing;
    
    -- Grant privileges
    GRANT ALL PRIVILEGES ON SCHEMA auth TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON SCHEMA user_service TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON SCHEMA inventory TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON SCHEMA sales TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON SCHEMA billing TO $POSTGRES_USER;
EOSQL
