version: '3.8'
services:
  app:
    build: .
    container_name: thelarte
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    container_name: thelarte-postgres
    environment:
      POSTGRES_DB: thelarte
      POSTGRES_USER: thelarte
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-thelartepwd}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
